### PR TITLE
SL-integration closes #308

### LINKED ISSUE #308: ER example sentence indexing with CoNLL reader
The reader indexes the sentences with the order of reading them and when we read two separate files for train and test, there are different sentences with same index, this makes a problem for edges between tokens and sentences which is done based on the sentence id, particularly for the candidate generation from relation to token it makes a bug. However this will not be a problem for cross validation setting.

### PR DESCRIPTION
**Pull request by kordjamshidi**
This is a new PR from #247

### CODE REVIEW

**Comment by kordjamshidi** [comment]
I am not sure what has changed in the recent versions of the Lbjava with the ILPInference, when using 24 I get this error: 
`Error:(6, 112) overloaded method constructor ILPInference with alternatives:
  (x$1: Any,x$2: edu.illinois.cs.cogcomp.infer.ilp.ILPSolver)edu.illinois.cs.cogcomp.lbjava.infer.ILPInference <and>
  (x$1: edu.illinois.cs.cogcomp.infer.ilp.ILPSolver,x$2: Int)edu.illinois.cs.cogcomp.lbjava.infer.ILPInference
 cannot be applied to (T, edu.illinois.cs.cogcomp.lbjava.infer.ILPSolver)
abstract class JointTemplate[T](head: T, solver: ILPSolver, norm: Normalizer = new IdentityNormalizer) extends ILPInference(head, solver) {
                                                                                                               ^`

**Comment by danyaljj** [comment]
is it compile error?

**Comment by kordjamshidi** [comment]
yes.

**Comment by danyaljj** [comment]
it is a package name change. Remove the import (on top of the file) and add the correct one.

**Comment by kordjamshidi** [comment]
It seems you have two copies of some of the classes in lbjava.infer and core.infer, right?

**Comment by danyaljj** [comment]
I think you just need to fix the package import  ...

**Comment by kordjamshidi** [comment]
I have it in many files, and some of them still get things from lbjava.infer

**Comment by kordjamshidi** [comment]
Too many package changes, I fixed the ones with `I/O` for Readers for pos tagger... but the ILPInference issue seems to be ok now!

**Comment by kordjamshidi** [comment]
where is this one? `PennTreebankPOSReader`

**Comment by danyaljj** [comment]
You don't really need to ask us; you can just search inside our super-project: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/corpusreaders/src/main/java/edu/illinois/cs/cogcomp/nlp/corpusreaders/PennTreebankPOSReader.java

**Comment by kordjamshidi** [comment]
You don't need to answer if too annoying!

**Comment by kordjamshidi** [comment]
I don't see this file in current Saul's cogcomp nlp!

**Comment by danyaljj** [comment]
Did this happen after changing the lbjava version? You need to see what is the latest "illinois-core-utils" and "corpus-readers" in your classpath.

**Comment by danyaljj** [comment]
if the issue is not resolved I can look at it tonight

**Comment by kordjamshidi** [comment]
No, thanks. It has been resolved.

**Comment by danyaljj** [comment]
@kordjamshidi is this functional/ready?

**Comment by kordjamshidi** [comment]
Actually, not yet, there is something wrong with the feature indexes that I could not resolve, so it does not generate the correct results for ER.

**Comment by kordjamshidi** [comment]
It was a while that I left it, but I will get back to it this weekend.

**Comment by danyaljj** [comment]
Could you elaborate more? 
Is it a very big issue? 
Does it make sense to merge the current version and then add the fixes later?

**Comment by kordjamshidi** [comment]
I don't think it is a big issue, it is related to concatenation of the feature vectors of various classifiers and making them one global vector. I do it but somewhere, something goes wrong with this module. It should be a small fix but needs a careful debug.

**Comment by danyaljj** [comment]
okei then let's aim at getting this reviewed and checked then, over the next week or so.

**Comment by kordjamshidi** [comment]
Ok, sure. Good idea.

**Comment by danyaljj** [comment]
Since we changed the semaphore account, it doesn't seem to be get triggered for this PR. Will close it and open another one.

**Pull request closed without merging**
