### PR TITLE
Webapp fix

### PR DESCRIPTION
**Pull request by bhargav**
- Updated content for Email Spam, Drug Response and Edison Features app.
- @danyaljj fixed the issue with Logger error during compilation.

Pending:
- Webapp unit tests are failing. Will investigate today.

Towards #381

### CODE REVIEW

**Comment by danyaljj** [comment]
Looks good to me.

**Comment by kordjamshidi** [comment]
I think: please make the main fix which is about failing tests before merge.

**Comment by danyaljj** [comment]
This PR will make the webapp **temporarily** functional.
Current webapp has significant issues that need to be addressed (e.g. #398) as well as the better tests to ensure the correct functionality. 
I would suggest moving on with this PR, and addressing other issues in future PRs, step by step.

**Comment by kordjamshidi** [comment]
are the test failing due to #398 ?

**Comment by danyaljj** [comment]
> are the test failing due to #398 ?

The tests are not failing because of that issue. They are failing due to some injection issue (which I am not sure how to fix). But that is not the point; Look at the current tests: https://github.com/IllinoisCogComp/saul/tree/master/saul-webapp/test 
Currently our webapp tests, have literally NOTHING.  Even if these tests work, they ensure NOTHING. 
We first have to add good/high-coverage test. And if we don't fix #398, we won't be able to have any meaningful tests.

**Comment by kordjamshidi** [comment]
Okaayy.

**Pull request merged**
